# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170121_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
