# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170121_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.AddField(
            model_name='team',
            name='id1',
            field=models.CharField(default='00000', max_length=12),
        ),
        migrations.AddField(
            model_name='team',
            name='id2',
            field=models.CharField(default='00000', max_length=12),
        ),
        migrations.AlterField(
            model_name='team',
            name='money',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
