# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170122_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id1',
            field=models.IntegerField(default=0, help_text='Paritcipant 1 ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id2',
            field=models.IntegerField(default=0, help_text='Paritcipant 2 ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.IntegerField(help_text='Team Number', primary_key=True, serialize=False),
        ),
    ]
