# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170123_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='id2',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
