# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170124_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.SmallIntegerField(default=0)),
                ('setprice', models.BooleanField(default=False)),
                ('Other_teamno', models.IntegerField(default=20001)),
            ],
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='SetPrice',
        ),
    ]
