# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170124_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_control',
            name='Other_teamno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
