# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170124_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('round_no', models.SmallIntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
                ('priceinitial', models.FloatField()),
                ('pricefinal', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='stock',
        ),
        migrations.RenameField(
            model_name='admin_control',
            old_name='setprice',
            new_name='trade_enable',
        ),
        migrations.AddField(
            model_name='team',
            name='mobile_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='id1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='id2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='StockList',
        ),
        migrations.DeleteModel(
            name='StockPrice',
        ),
        migrations.AlterUniqueTogether(
            name='stockinfo',
            unique_together=set([('name', 'round_no')]),
        ),
    ]
