# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170201_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id1',
            field=models.CharField(max_length=20),
        ),
    ]
