# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170317_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.SmallIntegerField(default=0)),
                ('exchange_rate', models.FloatField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='admin_control',
            name='starting_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='exchange_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='stocktype',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='exchange_rate',
            unique_together=set([('round_no', 'exchange_rate')]),
        ),
    ]
