# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170322_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='money',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='team',
            name='net_worth',
            field=models.IntegerField(default=100000),
        ),
    ]
