# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170325_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
